### ISSUE TITLE
ArchiverCheckTestCase race condition

### ISSUE THREAD

**Issue by enkore** [borgbackup/borg#2048]
```
________________ ArchiverCheckTestCase.test_corrupted_manifest _________________
[gw5] linux -- Python 3.6.0 /home/travis/build/borgbackup/borg/.tox/py36/bin/python3.6
self = <borg.testsuite.archiver.ArchiverCheckTestCase testMethod=test_corrupted_manifest>
    def setUp(self):
        super().setUp()
        with patch.object(ChunkBuffer, 'BUFFER_SIZE', 10):
            self.cmd('init', '--encryption=repokey', self.repository_location)
            self.create_src_archive('archive1')
            >           self.create_src_archive('archive2')
/home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:2050: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:258: in create_src_archive
    self.cmd('create', self.repository_location + '::' + name, src_dir)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:251: in cmd
    ret, output = exec_cmd(*args, fork=fork, exe=self.EXE, archiver=self.archiver, **kw)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:82: in exec_cmd
    ret = archiver.run(args)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/archiver.py:2843: in run
    return func(args)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/archiver.py:106: in wrapper
    return method(self, args, repository=repository, **kwargs)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/archiver.py:379: in do_create
    create_inner(archive, cache)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/archiver.py:352: in create_inner
    archive.save(comment=args.comment, timestamp=args.timestamp)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/archive.py:417: in save
    self.repository.commit()
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/repository.py:294: in commit
    self.compact_segments()
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/repository.py:576: in compact_segments
    complete_xfer(intermediate=False)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/repository.py:474: in complete_xfer
    segment = self.io.write_commit(intermediate=intermediate)
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/repository.py:1196: in write_commit
    fd = self.get_write_fd()
    /home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/repository.py:1006: in get_write_fd
    self._write_fd = SyncFile(self.segment_filename(self.segment), binary=True)
    src/borg/platform/linux.pyx:233: in borg.platform.linux.SyncFile.__init__ (src/borg/platform/linux.c:6477)
    ???
    _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <borg.platform.linux.SyncFile object at 0x7f99829eaf98>
path = '/tmp/tmpt6gf2j1r/repository/data/0/9', binary = True
    def __init__(self, path, binary=False):
        mode = 'xb' if binary else 'x'
        >       self.fd = open(path, mode)
E       IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpt6gf2j1r/repository/data/0/9'
/home/travis/build/borgbackup/borg/.tox/py36/lib/python3.6/site-packages/borg/platform/base.py:86: IsADirectoryError
----------------------------- Captured stderr call -----------------------------
```

**Comment by ThomasWaldmann** [comment]
another one:
```
==> wheezy32: _________________________ ArchiverTestCase.test_delete _________________________
==> wheezy32: [gw1] linux -- Python 3.6.0 /vagrant/borg/borg/.tox/py36/bin/python3.6
==> wheezy32: self = <borg.testsuite.archiver.ArchiverTestCase testMethod=test_delete>
==> wheezy32: 
==> wheezy32:     def test_delete(self):
==> wheezy32:         self.create_regular_file('file1', size=1024 * 80)
==> wheezy32:         self.create_regular_file('dir2/file2', size=1024 * 80)
==> wheezy32:         self.cmd('init', '--encryption=repokey', self.repository_location)
==> wheezy32:         self.cmd('create', self.repository_location + '::test', 'input')
==> wheezy32:         self.cmd('create', self.repository_location + '::test.2', 'input')
==> wheezy32:         self.cmd('create', self.repository_location + '::test.3', 'input')
==> wheezy32:         self.cmd('create', self.repository_location + '::another_test.1', 'input')
==> wheezy32:         self.cmd('create', self.repository_location + '::another_test.2', 'input')
==> wheezy32:         self.cmd('extract', '--dry-run', self.repository_location + '::test')
==> wheezy32:         self.cmd('extract', '--dry-run', self.repository_location + '::test.2')
==> wheezy32:         self.cmd('delete', '--prefix', 'another_', self.repository_location)
==> wheezy32:         self.cmd('delete', '--last', '1', self.repository_location)
==> wheezy32:         self.cmd('delete', self.repository_location + '::test')
==> wheezy32:         self.cmd('extract', '--dry-run', self.repository_location + '::test.2')
==> wheezy32: >       output = self.cmd('delete', '--stats', self.repository_location + '::test.2')
==> wheezy32: 
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:1097: 
==> wheezy32: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:251: in cmd
==> wheezy32:     ret, output = exec_cmd(*args, fork=fork, exe=self.EXE, archiver=self.archiver, **kw)
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/testsuite/archiver.py:82: in exec_cmd
==> wheezy32:     ret = archiver.run(args)
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/archiver.py:2843: in run
==> wheezy32:     return func(args)
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/archiver.py:106: in wrapper
==> wheezy32:     return method(self, args, repository=repository, **kwargs)
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/archiver.py:807: in do_delete
==> wheezy32:     return self._delete_archives(args, repository)
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/archiver.py:832: in _delete_archives
==> wheezy32:     manifest.write()
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/helpers.py:258: in write
==> wheezy32:     self.repository.put(self.MANIFEST_ID, self.key.encrypt(Chunk(data, compression={'name': 'none'})))
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/key.py:336: in encrypt
==> wheezy32:     self.nonce_manager.ensure_reservation(num_aes_blocks(len(chunk.data)))
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/nonces.py:86: in ensure_reservation
==> wheezy32:     self.commit_local_nonce_reservation(reservation_end, local_free_nonce)
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/nonces.py:34: in commit_local_nonce_reservation
==> wheezy32:     with SaveFile(self.nonce_file, binary=False) as fd:
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/platform/base.py:141: in __enter__
==> wheezy32:     self.fd = platform.SyncFile(self.tmppath, self.binary)
==> wheezy32: src/borg/platform/linux.pyx:233: in borg.platform.linux.SyncFile.__init__ (src/borg/platform/linux.c:6477)
==> wheezy32:     super().__init__(path, binary)
==> wheezy32: _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
==> wheezy32: 
==> wheezy32: self = <borg.platform.linux.SyncFile object at 0xb566c9ec>
==> wheezy32: path = '/tmp/pytest-of-vagrant/pytest-2/popen-gw1/xdg-config-home15/borg/security/504b1117e02b8548770d3e2e479ce880f555783a79d314fa92e33a86dae5bbdb/nonce.tmp'
==> wheezy32: binary = False
==> wheezy32: 
==> wheezy32:     def __init__(self, path, binary=False):
==> wheezy32:         mode = 'xb' if binary else 'x'
==> wheezy32: >       self.fd = open(path, mode)
==> wheezy32: E       IsADirectoryError: [Errno 21] Is a directory: '/tmp/pytest-of-vagrant/pytest-2/popen-gw1/xdg-config-home15/borg/security/504b1117e02b8548770d3e2e479ce880f555783a79d314fa92e33a86dae5bbdb/nonce.tmp'
==> wheezy32: 
==> wheezy32: .tox/py36/lib/python3.6/site-packages/borg/platform/base.py:86: IsADirectoryError
```

**Comment by ThomasWaldmann** [comment]
I've seen errors like these very often when I experimented with the new freebsd 10.3 vagrant VMs, while I used the freebsd fakeroot to run the tests ('fakeroot -u tox`).

I finally tried without fakeroot and these errors vanished.

So, do we have the same issue on linux, just less frequently?

**Comment by enkore** [comment]
What I find rather curious is that an open(O_EXCL|O_RDWR) fails with EISDIR. In some instances one can argue about this being a simple race condition, but here these are paths we most definitely never create directories at.

```
       EISDIR pathname  refers  to  a  directory  and  the  access  requested
              involved writing (that is, O_WRONLY or O_RDWR is set).

       EISDIR pathname  refers to an existing directory, O_TMPFILE and one of
              O_WRONLY or O_RDWR were specified in  flags,  but  this  kernel
              version does not provide the O_TMPFILE functionality.
```

**Comment by ThomasWaldmann** [comment]
Note: after analysis of the cause of this issue and its consequences, milestone might need to be adjusted to 1.1, if a 1.0-maint change is not rectified.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/issues/1340#issuecomment-284172217

**Comment by ThomasWaldmann** [comment]
https://bugs.python.org/file40824/tempfile_comment.patch

**Comment by ThomasWaldmann** [comment]
doesn't look like we can quickly solve this, pushing to next milestone.

**Comment by PlasmaPower** [comment]
The tests aren't multithreaded, right? `SaveFile.__enter__` first tries to unlink the tmppath before opening it. That would fail with an OSError if it was a directory. So, somehow, a directory gets created between when `SaveFile.__enter__` is called and when it calls `SyncFile.__init__`. Sounds suspicious to me, I might try to debug it with `strace -e trace=file`.

**Comment by PlasmaPower** [comment]
NVM, tests are being run simultaneously. I guess the next question is why are they overlapping with long random paths. Maybe the randomness is time based?

I could also have missed something, I'll see if the tests work when run one at a time.

**Comment by enkore** [comment]
The interesting thing is that these are often IsADirectoryError's, which IMHO does not make the least bit of sense. Note that if we'd have a race with O_EXCL, we'd get a FileExistsError. EISDIR should only be occur if the path *itself* refers to a directory in an invalid way.

**Comment by PlasmaPower** [comment]
Yeah, I got that part. Maybe there's a symlink? The only other possible explanation is that Python is returning the wrong error code. I'm running it in a loop with strace now. Strace should identify any of those problems, but it is slowing the tests down significantly, so it might be a while before it hits the race condition (if at all). Is there a good way in Python to intercept and log filesystem calls? That might be faster.

**Comment by ThomasWaldmann** [comment]
I suspect that this is a malfunction of fakeroot.

**Comment by enkore** [comment]
There are some results for race conditions in fakeroot. The hypothesis is if not supported, at least not contradicted, by no one seeing this error outside tox-fakeroot.

**Comment by PlasmaPower** [comment]
I agree a fakeroot problem (or at least unique difference) is very likely. Intercepting and logging syscalls would also help with that. Right now I'm working on building a mini strace that's a lot faster so we can reproduce the race conditions while logging syscalls.

**Comment by enkore** [comment]
Re. logging intercepting syscalls within the runtime: Not that I'm aware of. Python C extensions have made a habit of sprinkling syscalls all over the place, using LD-preloading or runtime patching (trampolines) is the only way there.

**Comment by PlasmaPower** [comment]
I've completed my mini syscall interceptor, and it doesn't seem to be slowing down the tests at all. Now to see if I can replicate the issue.

**Comment by PlasmaPower** [comment]
How frequently does the issue occur on Linux? I've been running it for 2 hours now (in a loop) and I still haven't hit a failure. I might have to setup a freebsd environment.

**Comment by enkore** [comment]
For me it looks like it most frequently happens on Travis. *When* I use tox+fakeroot... maybe one failure every 10-20 runs or so. It has been a while.

**Comment by PlasmaPower** [comment]
It looks like I've run the test suite 26 times. I've also disabled the fuse and attic tests. I'm assuming that won't interfere with anything. I'll keep running the tests for a while longer, then I'll see if I can replicate the issue on the base borg.

**Comment by PlasmaPower** [comment]
I'm now running the tests with `-n 8` (I have an 8 core CPU). Hopefully that'll make the error easier to reproduce.

**Comment by PlasmaPower** [comment]
I couldn't replicate the crash overnight. I'll try to setup a FreeBSD VM and see if I can replicate it there.

**Comment by PlasmaPower** [comment]
Just realized fakeroot uses LD_PRELOAD too and I was overriding it not prepending it, and the vagrant script doesn't use fakeroot by default. Oops. I've reproduced it, here are my conclusions:

The error does not appear to originate from fakeroot, or anything above the Python level. Here's the relevant info:

Here's the first py.test failure (I checked 2 to be safe though):

```py
>       self.fd = open(path, mode)
E       IsADirectoryError: [Errno 21] Is a directory: '/tmp/tmpjeoubp22/repository/data/0/1'
```

Searching for `tmpjeoubp22` (not the whole path) in the intercepts turns up only one file, `49863.34397512704.log`. `/tmp/tmpjeoubp22/repository/data/0/1` only appears once in the file. Here's the relevant excerpt:
```
00037.413369646 mkdir /tmp/tmpjeoubp22/repository/data/0 (mode: 511) -> 0, errno 2
00037.413533156 open /tmp/tmpjeoubp22/repository/data (flags: 1048576, mode: 511) -> 15, errno 2
00037.416349726 open /tmp/tmpjeoubp22/repository/data/0/0 (flags: 1051137, mode: 438) -> 15, errno 0
00037.521249553 open /tmp/tmpjeoubp22/repository/data/0 (flags: 1048576, mode: 511) -> 15, errno 0
00037.522074092 open /tmp/tmpjeoubp22/repository/data/0/1 (flags: 1051137, mode: 438) -> 15, errno 0
00037.522571331 open /tmp/tmpjeoubp22/repository/lock.roster (flags: 1048576, mode: 438) -> 15, errno 0
00037.523400343 open /tmp/tmpjeoubp22/repository/lock.roster (flags: 1050113, mode: 438) -> 15, errno 0
00037.524176807 open /tmp/tmpjeoubp22/repository/lock.roster (flags: 1048576, mode: 438) -> 15, errno 0
00037.524987650 open /tmp/tmpjeoubp22/repository/lock.roster (flags: 1048576, mode: 438) -> 15, errno 0
00037.743040522 open /tmp/tmpjeoubp22 (flags: 1048576, mode: 511) -> 15, errno 0
```

As you can see, the open call clearly works returning no errno. It's also not an errno timing issue (could that even happen?), because the errno remains 0 for the next few calls. It returns a valid file descriptor; I'm not even sure Python checks the errno in that case. Just to confirm, I also searched for errno 21 (is a directory). There were 3 results for these directories: `/tmp/tmp6p9uv3yw/output/input/file1`, `/tmp/tmpkh2hnaaz/output/input/file1`, and `/tmp/tmpwean9im2`. Those all appear to be valid cases of "is a directory".

If you're wondering, I'm currently intercepting `open`, `mkdir`, and `symlink` syscalls. I judged those to be possibly relevant to the problem (and I don't think Python uses any *at calls). I've put the code for the interceptor on GitHub: https://github.com/PlasmaPower/intercept-fs

I can upload the full logs and intercepts if wanted.

**Comment by PlasmaPower** [comment]
Just to double check, I tried appending my library to LD_PRELOAD (instead of prepending it) and I still got pretty much the same result.

**Comment by PlasmaPower** [comment]
I built a custom Python that puts a message in stderr whenever open encounters errno 21. It didn't happen for our broken tests. Turns out, errno 21 can also be generated if the file is a directory, even if it is in read mode. Since that's a perfectly valid `open` command, to prevent opening dirs and keep cross platform support Python throws an error later (even though errno isn't set). Example:

```
>>> open("/", "w")
Received valid EISDIR for path /
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IsADirectoryError: [Errno 21] Is a directory: '/'
>>> open("/", "r")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IsADirectoryError: [Errno 21] Is a directory: '/'
```

I've finally narrowed down exactly where the error is being generated. Now to figure out why.

**Comment by PlasmaPower** [comment]
I updated my interceptor to intercept all forms of stat (tricky as `stat` is actually a macro for `__xstat` on Linux, but not FreeBSD) and reran the tests with it. Turns out fakeroot might be messing with something after all. Here's another intercept section for a EISDIR error:

```
00112.141335560 open /tmp/tmp8nrcs1zl/repository/data/0/32 (flags: 1051137, mode: 438) -> 18, errno 0
00112.141398977 fstat 18 -> mode 16832 uid 0 gid 0 size 0 -> 0
```

Let's look at that mode: in octal it's 40700. That's `S_IFDIR | S_IRWXU`, or in other words, a directory with permissions `700` - in chmod notation `u+rwx`. That shouldn't be happening. The mode in the previous open call is `666` in octal, or `a+rw`. It was also passed `O_CREAT`, and it hadn't been mentioned earlier in the logs. I see every reason it should be a file, and no reason for it to be a directory. It looks like it is a fakeroot bug after all.

**Comment by PlasmaPower** [comment]
Has anyone encountered this error on a fakeroot 1.21 system? My desktop is fakeroot 1.21 but the VM is fakeroot 1.20, and I can only reproduce it in the latter.

**Comment by enkore** [comment]
Impressive investigation!

1.21 vs 1.20: Might well be it. I *thought* I have seen it very few times on my system, but that would have always had 1.21. Perhaps I ran it via Vagrant in these cases and just mis-remember it.

**Comment by enkore** [comment]
Re. strace slowdown - I think this is due to strace using `ptrace` to intercept syscalls, which would incur, in my mind, at least two extra context switches, whereas your approach (nice!) runs in the same process by overriding libc's symbols.

**Comment by PlasmaPower** [comment]
Re. Re. strace slowdown - yeah I figured that out eventually, after the strace/__xstrace issue.

I'm still not sure if the difference lies in fakeroot versions, but I'd prefer to have a single version to investigate, and I'd prefer it to be the newest one if possible.

**Comment by PlasmaPower** [comment]
I'm not sure how complete it is, but I don't see anything in the fakeroot changelog that might have fixed this: https://launchpad.net/debian/+source/fakeroot/+changelog

**Comment by enkore** [comment]
Borg previously hit some bug in fakeroot I investigated and that one was fixed with no notice in the changelog as well.

**Comment by enkore** [comment]
Perhaps #1899 is the same fakeroot bug

**Comment by PlasmaPower** [comment]
I just diffed the source files between 1.20 and 1.21, and it would appear the only change that isn't docs or build tools is increasing `MAX_IPC_BUFFER_SIZE` from 256 to 1024. I doubt the problem lies there.

**Comment by PlasmaPower** [comment]
IT looks like there's a debug mode for faked, and it can be enabled as follows: `fakeroot -f 'faked --debug' ...`. However, it doesn't appear to be working in freebsd. I'm not sure if it's disabled or what, but I'm just going to rebuild it. That way it'll also get fakeroot 1.21.

**Comment by PlasmaPower** [comment]
It still doesn't seem to be printing debug info, I think it might have to do with using the USR1 signal to trigger printing out debug info. It's odd that it works by default locally but not in the FreeBSD machine. It's also a bit hard to manage fakeroot/faked/libfakeroot.

**Comment by PlasmaPower** [comment]
I got `faked` debugging working. It's receiving a chmod 0o40700 from the client, but that's not mirrored in any syscall. It might be generated when the file is created, but I don't know why it decided on it being a directory.

**Comment by PlasmaPower** [comment]
Fakeroot is proving impossible to read, functions definitions are split across multiple autogenerated files. If anyone could find out how the open function works that'd be great.

**Comment by PlasmaPower** [comment]
It looks like I had a misunderstanding of fakeroot - it doesn't only apply to files created under the same fakeroot session, it applies to any file owned by the user running it. It therefore needn't intercept open calls. I also discovered fakeroot debugging, I'm going to build that into the freebsd fakeroot the rerun the tests.

**Comment by PlasmaPower** [comment]
I'm having trouble getting the libfakeroot debug logging to work as it's to stderr from libfakeroot so anything logged will get caught up by the borg test suite and break everything. However, I did do a bit more research into the faked source, and it looks like faked will refuse to change the file type with chmod. I think it's most likely that faked does not realize the file exists when it gets the chmod request (not the source of the race condition though - if it realizes it got an incompatible mode it logs it to stderr).

I was thinking about creating a minimal fakeroot for our use, when I came up with the name "pseudo". I googled it, and guess what, there's already an actively maintained fakeroot replacement named that: https://git.yoctoproject.org/cgit/cgit.cgi/pseudo/about/

We might want to consider either switching to another fakeroot project or creating our own, as it seems fakeroot has been causing us a lot of trouble. Creating our own would require maintenance, but we'd be able to quickly debug and fix issues at least. If we use a replacement we run the risk of it going out of use. I'm not sure there's a great option, so we might want to just stick with fakeroot for now.

**Comment by PlasmaPower** [comment]
Might be fixed with #2478

**Comment by PlasmaPower** [comment]
We should probably close this and the other traceback issues.

**Comment by enkore** [comment]
I'll leave this one closed, since the investigation showed that this is not a race condition in the Borg test suite or py.test.

Fixing the issue is #2482.
